### ISSUE TITLE
Program error

### ISSUE THREAD

**Issue by Marc34** [jonathan-markland/Jynx#13]
I try to use your program on linux. I have build it but I have this message :

"The program cannot continue running because of an internal error:
'One or more of the ROM files are missing or damaged.  Please refer to the readme.htm file for information.'"

And in the terminal :

(Jynx:5660): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(Jynx:5660): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(Jynx:5660): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(Jynx:5660): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

Thank for your help.

**Comment by jonathan-markland** [comment]
Hi Marc 

Sorry about the very very late reply!!! 

You need to go to my wordpress blog:  https://jynxemulator.wordpress.com/
Go to the downloads tab, and get the binary from my dropbox. The ROM files are in the binary.
I do not put the ROMs into the repository, because I don't want to risk a take-down notice for the emulator source code!

Jonathan.

**Comment by Marc34** [comment]
ok, thank !
